### ISSUE TITLE
As a user, I want to open the sidebar view using a command.

### ISSUE THREAD

**Issue by mcndt** [mcndt/obsidian-toggl-integration#11]
In case I accidentally closed it or it is missing from my Obsidian workspace layout.

**Comment by tonyxiao** [comment]
Is there a way to open it once it's been closed short of re-starting the whole Obsidian workspace?

Also, how often is the sidebar view refreshed?

**Comment by mcndt** [comment]
> Is there a way to open it once it's been closed short of re-starting the whole Obsidian workspace?

Currently no, I implemented the sidebar view a bit heavy handedly as I wanted to push out the plugin before my current internship started. However, you can quickly reload the application using the command palette option "Reload app without saving" in case you did close the view.

> Also, how often is the sidebar view refreshed?

I answered this in your other issue :)

**Comment by mcndt** [comment]
Will be released in 0.12.0
