### ISSUE TITLE
How to get multitask timetrack done.

### ISSUE THREAD

**Issue by 3ark1o1** [mcndt/obsidian-toggl-integration#111]
Like below.
[track time simultaneous 2 or more tasks - Feature Requests, Suggestions - Hitask Community](https://community.hitask.com/t/track-time-simultaneous-2-or-more-tasks/974/2)

respect.

**Comment by StanczakDominik** [comment]
This would probably be something to take up with the Toggl folks. As it's not supported by them, I don't expect it'd be something the plugin should try to force in.
