### ISSUE TITLE
[[Feature request]] : stop timer 

### ISSUE THREAD

**Issue by joniac1** [mcndt/obsidian-toggl-integration#115]
It would be great to stop the timer without finishing the task, and then able to start it again.

**Comment by StanczakDominik** [comment]
You can already sort of do this. You do have to re-select the recently tracked task, though.

Otherwise, this is not supported by Toggl itself, so... probably out of scope for this plugin.

**Comment by mcndt** [comment]
I think @StanczakDominik's solution is how I intended it, not sure what else can be added here.
