### ISSUE TITLE
Reports show time entries for all users in a workspace

### ISSUE THREAD

**Issue by cdadd** [mcndt/obsidian-toggl-integration#117]
Currently reports show time entries by all users in a workspace. Would appreciate a way to filter to just your own entries or at least group by person.

**Comment by cdadd** [comment]
Confirmed this is no longer an issue in latest version (0.10.0)

**Comment by mcndt** [comment]
Thanks for following up!

**Comment by jds3v1** [comment]
How did this get resolved? I have 0.11.0 and it is still showing all users data.
