### ISSUE TITLE
Project title missing

### ISSUE THREAD

**Issue by bwuzhang** [mcndt/obsidian-toggl-integration#128]
No project title is shown for me. I'm using version 0.10.0.

```toggl
summary week
```

<img width="738" alt="image" src="https://user-images.githubusercontent.com/8942063/231936624-7fa6e9e9-0c17-4821-af12-b2b7faa25751.png">

**Comment by mcndt** [comment]
Hey, have you been consistently running into this issue? Or did reloading Obsidian resolve your problem?

**Comment by bwuzhang** [comment]
Yeah it fixed itself for no reason. :)
