### ISSUE TITLE
annoying error offline message 

### ISSUE THREAD

**Issue by joniac1** [mcndt/obsidian-toggl-integration#131]
The following message when you are offline is annoying : "Error communicating with Toggle API: Error:net::ERR_INTERNET_DISCONNECTED"

**Comment by sirlaughalot90** [comment]
Plus 1! Sometimes, I am in the situation that there is no Wifi or that it is not working (e.g. on the train) and this error message makes working impossible. I always have to disable the plugin in these circumstances.

**Comment by mcndt** [comment]
Yeah this one annoys me quite a bit as well 👍 

Will look into it soon

**Comment by mcndt** [comment]
Fixed in release 0.11.0
