### ISSUE TITLE
Creating new projects within Obsidian

### ISSUE THREAD

**Issue by ricraftis** [mcndt/obsidian-toggl-integration#133]
I cannot find anywhere in the documentation or notes on how to create a new project. Calling up the Command palette, select new timer and then a project has to be created if one doesn't already exist. Presently, I am using the Toggl app to create new projects. What am I missing here?

**Comment by mcndt** [comment]
You're correct, you cannot create projects from the plugin directly. For now this is not in scope of the plugin; the Obsidian integration's main goal is a convenient way to interact day-to-day with Toggl and quickly generate reports. It's not intended as a total replacement for the Toggl web application.
