### ISSUE TITLE
Stuck at "Loading Toggl report"

### ISSUE THREAD

**Issue by TeambitDK** [mcndt/obsidian-toggl-integration#136]
Hi 
After using the plug-in for a few days on different pc's, I return to my work pc to log time. But today the plug-in don't seem to want to render any reports in Obsidian. It's stuck at the "Loading Toggl report" animation. I'm not getting any errors, unless I write a faulty query.  I don't really have anything to go on at the moment. I'm using the newest plug-in (0.10.0), just tried to reinstall it, but no luck as of yet. Anyone else having the same issue? Any pointers would be great!

![image](https://github.com/mcndt/obsidian-toggl-integration/assets/38103036/4b0800ff-2c31-40cb-89cb-e78bb6bdc271)

Thanks in advance
/Olliver

**Comment by mcndt** [comment]
Hi Olliver! I have not experienced any issues with this myself this week. Have you gather any more information since when you posted your issue?

**Comment by TeambitDK** [comment]
I switched to another theme, and that seemed to do the trick. I haven't been able to reproduce the issue since. I was using the theme "Everforest" at the time, but even switching back to that theme, I've been unable to reproduce the issue. I think it can be considered closed for the time being.
