### ISSUE TITLE
Cannot Connect to Toggle API

### ISSUE THREAD

**Issue by Liong1976** [mcndt/obsidian-toggl-integration#15]
Since yesterday, this plugin didn't work. It says 

![image](https://user-images.githubusercontent.com/88898230/130229187-0ab6390c-52a4-44f4-a7cf-186236d7b710.png)

Even though it had worked very well before.

**Comment by mcndt** [comment]
I just published a hotfix for this issue (version 0.2.4)! You can update it from the Obsidian plugin marketplace. Let me know if that fixes it for you.

The Toggl team seems to have made some changes to their API without notifying users which caused all my requests to be blocked automatically.

**Comment by Liong1976** [comment]
Thanks a lot for your prompt fix! I do appreciate it
