### ISSUE TITLE
API unreachable error with success notification, not sure how

### ISSUE THREAD

**Issue by psychsatani** [mcndt/obsidian-toggl-integration#16]
I am new to toggl so not sure if this is a toggl issue or something to do with the plugin. Sidebar says toggl API is unreachable but in the plugin settings the connection is a success. (Attached video)

https://user-images.githubusercontent.com/78266798/130259307-eeac20ba-360e-47bd-b54b-77c93ff0a068.mov

**Comment by mcndt** [comment]
Please make sure you are on version 0.2.4 of the plugin, there were issues with the Toggl API since yesterday causing the plugin to break and I released a fix today. 

If that doesn’t fix it let me know!

**Comment by psychsatani** [comment]
Yes I was hoping this update will fix it. Before the update the settings page had no success notification. Now I have success notification but the error message hasn't gone from side pane. Tried uninstall and reinstall as well.
