### ISSUE TITLE
Decrease the amount of request to the `/api/v8/time_entries/current` endpoint

### ISSUE THREAD

**Issue by gilberthdez** [mcndt/obsidian-toggl-integration#17]
Greetings from Toggl Track👋 

Thanks for creating this integration for the Obsidian users and for adding a custom User-Agent.

We have detected that his integration is doing a lot of request GET to the `/api/v8/time_entries/current` endpoint. Looks like the frequency is ~1 request per second. 

A good rate in terms of UX for this request(refreshing what's the current time entry) is 1 request between 5-15s.

Help us(and the users) lowering this rate. Thanks :)

**Comment by mcndt** [comment]
Hey! Thanks for letting me know. I will lower the rate and push a patch to the Obsidian plugin marketplace.

Is this the reason my users were getting a 418 response from the API last week? If so, I would like to humbly ask your team to consider adding a more meaningful error response than "I'm a teapot" 😅 this way I would have known earlier to lower my polling rate.

**Comment by gilberthdez** [comment]
>Is this the reason my users were getting a 418 response from the API last week? If so, I would like to humbly ask your team to consider adding a more meaningful error response than "I'm a teapot" 😅 this way I would have known earlier to lower my polling rate.

That's correct and sorry for that. We weren't able to identify the source since the request were using the default `got` user-agent. 😅 

Thanks for the quick response!

**Comment by mcndt** [comment]
Fixed in release 0.2.5. I'll make a post in the Obsidian discord community to ask my users to update when they can.

Obviously this makes the plugin a little less responsive (I reduced the polling interval to 6s). Are there smarter ways to get active timer updates than periodically pinging the API?

**Comment by gilberthdez** [comment]
>Obviously this makes the plugin a little less responsive (I reduced the polling interval to 6s). Are there smarter ways to get active timer updates than periodically pinging the API?

At the moment we don't offer any other option for 3rd parties. But there's a chance that changes in the future 👍 

thanks for attending this request 🙌 .
