### ISSUE TITLE
Sidebar list periodically clears and only current activity shows

### ISSUE THREAD

**Issue by macbikegeek** [mcndt/obsidian-toggl-integration#34]
The sidebar list of activities periodically clears during the day and only current activity shows. It's intermittent and I haven't determined a trigger that causes it. 

Minor but it would be nice if the list stay. Love the plugin!

**Comment by mcndt** [comment]
@macbikegeek Thanks for reporting this bug! Could you add a screenshot of the bug to this thread the next time it occurs for you? I use the plugin daily myself and I have not encountered this bug yet, so I need some help to pin this one down.

**Comment by macbikegeek** [comment]
<img width="434" alt="Screen Shot 2021-11-03 at 2 32 38 PM" src="https://user-images.githubusercontent.com/20144822/140255200-e4e76084-192c-425c-8beb-8330887912d4.png">
<img width="442" alt="Screen Shot 2021-11-03 at 11 49 51 PM" src="https://user-images.githubusercontent.com/20144822/140255279-c544364e-4e58-4d50-b8f1-f919cfae25f3.png">

From Obsidian console:
Case 2: old timer -> new timer (new ID)
2TogglManager.ts:311 Case 3: timer details update (same ID)
2TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
2TogglManager.ts:311 Case 3: timer details update (same ID)
2TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
3TogglManager.ts:311 Case 3: timer details update (same ID)
2TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
2TogglManager.ts:311 Case 3: timer details update (same ID)
2TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:318 Case 4: active timer -> no timer
TogglManager.ts:296 Case 1: no timer -> active timer
client.js:86 Uncaught (in promise) Error: Toggl API responded with status code 502. Response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at TogglClient.request (eval at <anonymous> (app.js:1), <anonymous>:9345:13)
    at async TogglClient.get (eval at <anonymous> (app.js:1), <anonymous>:9324:12)
    at async TimeEntries.current (eval at <anonymous> (app.js:1), <anonymous>:9048:20)
TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:301 Case 2: old timer -> new timer (new ID)
4TogglManager.ts:311 Case 3: timer details update (same ID)
TogglManager.ts:301 Case 2: old timer -> new timer (new ID)

**Comment by cansar** [comment]
I had this issue yesterday (first day with the plugin). I'll keep an eye on it today and report any error logs if it happens again.

Also, thank you for creating this, it's exactly what I'd been looking for for years.

**Comment by mcndt** [comment]
Funnily enough I just encountered this issue for the first time myself as I am making frequent API requests while developing report blocks (#27). I think I know what the issue is, so I'll try to write a fix and add it in the next release.

The gist of it is that I don't handle failing API requests gracefully causing the display to go empty until the next request. The frequency at which this occurs is of course entirely dependent on how well your machine can reach the Toggl servers, which is why I hadn't seen it yet.

**Comment by macbikegeek** [comment]
Thanks, @mcndt! Glad you found the issue.

**Comment by mcndt** [comment]
I think I fixed the issue, although I cannot verify it because I don't have the proper tooling set up to mess with the API requests. 

Don't hesitate to reopen the issue if you still encounter this bug!

**Comment by macbikegeek** [comment]
@mcndt I had the problem showing when I got the email for your fix notice. I updated the plugin and restarted Obsidian and the problem has not recurred. Thanks!
Lee
