### ISSUE TITLE
As a user I would like to be able to filter on client in markdown blocks

### ISSUE THREAD

**Issue by davidolrik** [mcndt/obsidian-toggl-integration#39]
When embedding a summary in a page it would be nice to be able to filter on "client".

Like so:

```
``toggl
summary week
client <client-name>
``
```

**Comment by mcndt** [comment]
Hi David,

Currently you can already filter by project using the syntax `{INCLUDE|EXCLUDE} PROJECTS "Project 1"[, "Project 2", ...]`

I can easily extend this to clients via `{INCLUDE|EXCLUDE} {PROJECTS|CLIENTS} "Project 1"[, "Project 2", ...]`

I'll try to look into this by next week. Hope you like the update!

**Comment by davidolrik** [comment]
That would be awesome! - And I love the update!

**Comment by mcndt** [comment]
Available in release 0.5.0: https://github.com/mcndt/obsidian-toggl-integration/releases/tag/0.5.0

I added both filtering and grouping by clients. Let me know if you encounter any problems.

**Comment by davidolrik** [comment]
Works like a charm!
