### ISSUE TITLE
View Tags as part of reports

### ISSUE THREAD

**Issue by aventuraviper** [mcndt/obsidian-toggl-integration#44]
It would be great if reports could have the option to display tags.

Understand reports are new and you are busy!

**Comment by mcndt** [comment]
Hi, I'm thinking of how to implement this. Currently I stack entries with the same description for brevity:

![image](https://user-images.githubusercontent.com/23149353/149401512-124e3a1a-a133-4540-9270-a87365aa878f.png)

What would this stacking behavior look like when the descriptions are the same, but the applied tags are different?

What makes more sense here: stacking regardless and merging all tags in the stack, or deduplicating entries that have different tag sets.

**Comment by aventuraviper** [comment]
> What would this stacking behavior look like when the descriptions are the same, but the applied tags are different?

That's a good question. I personally wouldn't have an issue with the stacking because there is unlikely to be entries with the same description but different tags (at least in my current workflow). Of course, other's may use Toggl differently but if the description itself is the same, I would have thought likely that the tags match.

If the tags didn't match, perhaps a 2-level stack? I.e. group by project as H1, then H2 being tags?

**Comment by mcndt** [comment]
Implemented and published in version 0.7.0. Let me know if you have any further feedback!
