### ISSUE TITLE
Feature Request: Queue API Calls

### ISSUE THREAD

**Issue by MalignantCarp** [mcndt/obsidian-toggl-integration#50]
Definitely enjoying being able to reduce one more application I need to have running through my various workflows, so many thanks for the plugin. I had almost given up on using Toggl, to be honest, but this certainly helped me keep the tool. :)

However, I like to have a landing page with a number of different summary queries that shows me kind of a bird's eye view of my productivity, which inevitably leads to:

![image](https://user-images.githubusercontent.com/93364935/149244179-a73a1f73-1687-4574-9650-4ea40c220182.png)

I suspect this is because there are 6 blocks of toggle queries on the one page and I am assuming they are all being sent at the same time. If they were instead entered into a queue and only one or two queries sent at once with their blocks being updated once data is returned, that would probably eliminate this problem. It would delay the appearance of the queries, but at least they could appear in the appropriate order. Right now they randomly fail. 😂 

I wouldn't consider this vital. I can probably cull one or two of the queries, but it would be a nice safeguard to enter into the system at some point.

**Comment by mcndt** [comment]
Interesting. Yeah implementing a queue system would require a bit more engineering work so I'll have to see when I can fit this in.

As a 'workaround', what I have done is have one main note for collecting time reports, which contains links to notes that contain reports on specific topics:

![image](https://user-images.githubusercontent.com/23149353/149378376-6c0eb1e3-aeb8-4adc-8e35-cd27ba5c03e3.png)

Each page contains just one or two report blocks.

I do recognize this as an issue though, and I'll see what I can do about it!

**Comment by mcndt** [comment]
I haven't stress tested this, but in the new version 0.8.0 reports are cached during your user session. Let me know if this helps this problem.

I'm closing this issue for now, but feel free to reopen or comment if your troubles persist.
