### ISSUE TITLE
Summary Report in Daily Note Format

### ISSUE THREAD

**Issue by pickleton89** [mcndt/obsidian-toggl-integration#51]
I would like to have the toggl summary as part of my daily, not template. However, I can't figure out how to have that day's date pulled into the query. For example, if I use "TODAY" it will only show the current day's summary, not the day for that note. Is there a variable or some special syntax that I can add to match the date of the daily note into the toggl summary?
Thanks in advance for the help.

**Comment by mcndt** [comment]
I see you already closed the issue, but in case you still need help, you can look into this: https://help.obsidian.md/Plugins/Templates#One-off+date+formats

**Comment by pickleton89** [comment]
If I put that {{date}} in the toggl block it throws an error. 
```toggl
SUMMARY {{date}}
```
If I use
```toggl
SUMMARY TODAY
```
In the daily notes, it will always show the current date, no matter what daily note, from the past, that I open. I thought I saw a feature request for this, so I closed the issue after I opened it.

**Comment by mcndt** [comment]
`{{date}}` only gets filled in once you instance a note from a template. I'll create a demo for you:



Example:

In your daily note template, add a codeblock with

~~~
```toggl
SUMMARY FROM {{date:YYYY-MM-DD}} TO {{date:YYYY-MM-DD}}
```
~~~

When you create a _new_ daily note from this template, it will look like this:

~~~
```toggl
SUMMARY FROM 2022-01-13 TO 2022-01-13
```
~~~

You can further customize the report by adding a custom title:

~~~
```toggl
SUMMARY FROM {{date:YYYY-MM-DD}} TO {{date:YYYY-MM-DD}}
TITLE "Summary for {{date:YYYY-MM-DD}}"
```
~~~

![Obsidian_XEmj7Th3OM](https://user-images.githubusercontent.com/23149353/149380144-dc46712a-52fd-48ec-9cc3-5698d319786d.gif)

**Comment by pickleton89** [comment]
Thank you. That worked. Much appreciated.
