### ISSUE TITLE
Feature Request: Sort Entries under date in LIST mode

### ISSUE THREAD

**Issue by MalignantCarp** [mcndt/obsidian-toggl-integration#55]
At present, it would appear that the entries under each date in LIST mode are in descending order. I'm not sure of the Toggl API sends the necessary information to change the sort order for these, but it would be nice to have them in ascending order to the first entry is displayed first:

![image](https://user-images.githubusercontent.com/93364935/150373469-714ecf92-5c56-431e-a565-dca742080f22.png)

You can see from the image, the dates are ascending, but the order in which the entries are displayed is reversed. Project Creation was first, followed by Author Photo Touchup, Main Titles, and then Blasted Crown.

**Comment by mcndt** [comment]
Oops! That's definitely not intended. I'll see if I can fix that for you soon.

**Comment by mcndt** [comment]
Fixed in version 0.6.1. 

Don't hesitate to report more feedback if you run into anything 😄
