### ISSUE TITLE
timer-start-button has the same  color -button-fill-inner and --button-fill-outer in some minimal  theme color schemes in dark mode

### ISSUE THREAD

**Issue by danieltomasz** [mcndt/obsidian-toggl-integration#67]
In color schemes default, dracula, nord  and polarized  the "start" button has one color button -  the same color of  `--button-fill-outer` and `--button-fill-inner`, the inner part (triangle) become visible when hoovering on the button

 The rest - atom, gruvbox, macos and  others are ok
The difference
![image](https://user-images.githubusercontent.com/7980381/154808484-44253a69-63ad-412e-b4a6-c08dec4e0e9b.png)

The light theme doesn't seem to be affected, only dark

**Comment by mcndt** [comment]
Hi Daniel,

Thanks for documenting the issue on GitHub! 

This is an accessibility issue and I'll try to make some time to find a color combination that contrasts better in any theme.

**Comment by mcndt** [comment]
![image](https://user-images.githubusercontent.com/23149353/155199115-bc6dd4e1-389a-437d-bb8d-a5f039ef1eea.png)

Will be fixed in version 0.7.2

**Comment by mcndt** [comment]
Released! Let me know if you have any further issues.
