### ISSUE TITLE
Daily summary for the daily note

### ISSUE THREAD

**Issue by mmfs37** [mcndt/obsidian-toggl-integration#79]
I am so sorry for asking this, because I have the feeling that this was asked thousand times before me. I couldn't find anything.

I do want in my daily obsidian note the summary of that day.

I thought I could just 
```toggl
summary 2022-04-04
```
and do that day with templater plugin. But it doesnt work that easily

![image](https://user-images.githubusercontent.com/100991030/161605747-250b7e9d-ece6-42ff-ab51-a727b4ac913c.png)
I need to give an interval expression. I cant just say day: 2022-04-04

I can ofc say 
```toggl
summary From 2022-04-04 To 2022-04-04
```

But is there a smoother way so it is not that ugly at the daily page?
![image](https://user-images.githubusercontent.com/100991030/161605974-d84b6040-14c8-4aeb-87e7-0a0cef077a30.png)
I think the heading with telling the name twice looks a bit trashy

**Comment by mcndt** [comment]
Hi! You're right that you have to do a TO ... FROM ... with the same date. However you can customize the report title to be anything you want by ending your query with TITLE "your title here". You can make that templated using Templater as well. Check the repo's wiki page for more documentation :)
