### ISSUE TITLE
As a user, I want to start a timer with description from text selection (using context menu)

### ISSUE THREAD

**Issue by mcndt** [mcndt/obsidian-toggl-integration#9]

**Comment by StanczakDominik** [comment]
Hey, could I ask if this is indeed "closed as completed"? IIRC, GitHub split issue closures between "closed as completed" and "closed as unplanned" ~last year. I'd be quite interested in doing this, but haven't been able to find any information on how to do this.

Unless this is not done, in which case, would you still be open to a pull request? 😄

**Comment by mcndt** [comment]
Hey! Yeah I closed this as unplanned; it's not a feature. 

I'd be delighted to approve a pull request!
